[tool.black]

line-length = 120
target-version = ["py310"]
include = '\.pyi?$'

[tool.pytest.ini_options]

timeout = 360
addopts = "-rx -rf -x -q --full-trace"
testpaths = ["tests"]

markers = [
    "slow: Marks test as being slow",
    "has_gpu: Marks test as requiring a GPU to run",
    "multi_gpu: Marks tests as requiring multiple GPUs to run",
    "has_mps: Marks test as requiring an MPS device to run",
    "has_triton: Marks test as requiring Triton to run",
]

[tool.mypy]

pretty = true
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true
disallow_untyped_defs = true
strict_equality = true
allow_redefinition = true

warn_unused_ignores = true
warn_redundant_casts = true

incremental = true
namespace_packages = false

# For TorchScript stuff.
disable_error_code = ["attr-defined"]

[[tool.mypy.overrides]]

module = [
    "torchaudio.*",
    "torchvision.*",
]

ignore_missing_imports = true

[tool.isort]

profile = "black"

[tool.ruff]

select = ["ANN", "D", "E", "F", "I", "N", "PGH", "PLC", "PLE", "PLR", "PLW", "W"]

ignore = [
    "ANN101", "ANN102", "ANN401",
    "D101", "D102", "D103", "D104", "D105", "D106", "D107",
    "N812", "N817",
    "PLR0911", "PLR0912", "PLR0913", "PLR0915", "PLR2004",
    "PLW0603", "PLW2901",
]

line-length = 120
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py310"

[tool.ruff.per-file-ignores]

"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.isort]

known-first-party = ["rwkv", "tests"]
combine-as-imports = true

[tool.ruff.pydocstyle]

convention = "google"
