name: Publish Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish:
    timeout-minutes: 10
    name: Build and publish

    # We don't need to run on all platforms since this package is
    # platform-agnostic. The output wheel is something like
    # "ml_starter-<version>-py3-none-any.whl".
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Build package
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
